blank_issues_enabled: false
contact_links:
  - name: Documentation issue
    url: https://github.com/Lomkit/laravel-rest-api-doc
    about: For documentation issues, open a pull request at the lomkit/laravel-rest-api-doc repository