name: Question / Enchancement proposal
description: "Ask a question or for a feature"
body:
  - type: textarea
    attributes:
      label: Description
      description: Leave a comment
    validations:
      required: true